print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill? $"))
tip_perc = int(input("What percentage tip would you like to give? 10, 12, or 15?"))
no_people = int(input("How many people will split the bill?"))
contribution = round((total_bill + (total_bill * tip_perc /100)) / no_people, 2)
print(f"Each person should pay: ${contribution}")